Repository JoyStream/joystream-desktop, pull requests merged in 2018-03, with the labels that each got.

#784 Use proper Map access
  src/core/Torrent/Statemachine/Torrent.js
Labels: bug

#785 Drop support for preferences in menu
  src/index.js
  src/menu.js
Labels: enhancement

#801 enhance(WalletSceneStore): rank payments by recency
  src/scenes/Wallet/Stores/WalletSceneStore.js
Labels: UX, Wallet, enhancement

#805 Use CashAddress format
  package.json
  src/scenes/Wallet/CashAddressFormat.js
  src/scenes/Wallet/Components/PaymentsTable/PaymentRow.js
  src/scenes/Wallet/Components/ReceiveDialog/ReceiveDialog.js
  src/scenes/Wallet/Components/SendDialog/SendDialog.js
  src/scenes/Wallet/Components/SendDialog/UserProvidingRecipientAddressForm/AddressInputField.js
  src/scenes/Wallet/Stores/ReceiveDialogStore.js
  src/scenes/Wallet/Stores/SendDialogStore/UserProvidingRecipientAddressFormStore.js
  test/core/CashAddressFormat/index.js
Labels: UX, Wallet

#802 Add terms acceptance scene
  package.json
  src/core/Application/Application.js
  src/core/ApplicationSettings/ApplicationSettings.js
  src/index.js
  src/scenes/Application/Application.js
  src/scenes/Application/Stores/ApplicationNavigationStore.js
  src/scenes/Onboarding/WelcomeScreen/WelcomeScreen.js
  src/scenes/Terms/TermsScreen.js
  src/scenes/Terms/index.js
  src/scenes/UIStore.js
  src/scenes/VideoPlayer/VideoPlayerScene.js
  test/core/ApplicationSettings/ApplicationSettings.js
Labels: UI, enhancement

#829 fix: replace all user interface BTC units to BCH
  src/common/common.js
  src/scenes/Application/components/ApplicationHeader/WalletPanel.js
  src/scenes/Wallet/Components/PaymentsTable/PaymentRow.js
  src/scenes/Wallet/Components/SendDialog/TakingUserInputForm.js
  src/scenes/Wallet/Components/SendDialog/UserProvidingAmountForm/UserProvidingAmountForm.js
Labels: UI

#832 Wallet: correctly compute the total and pending balances
  src/core/Wallet/Wallet.js
  src/scenes/Wallet/Stores/WalletSceneStore.js
Labels: Wallet, bug

#819 Wallet UI - UserProvidingAmount amounts in satoshi always an integer
  src/scenes/Wallet/Stores/SendDialogStore/UserProvidingAmountFormStore.js
Labels: Wallet

#835 Bch notice
  src/assets/img/bitcoin-cash.png
  src/constants.js
  src/scenes/Onboarding/Stores/OnboardingStore.js
  src/scenes/UIStore.js
  src/scenes/Wallet/Components/BCHInformationNotice/index.js
  src/scenes/Wallet/Components/BCHInformationNoticeSceneContent.js
  src/scenes/Wallet/Components/WalletScene.js
  test/ui/OnboardingStore/index.js
Labels: Onboarding, UX, Wallet, enhancement

#839 Adding fiat to payment rows
  package.json
  src/component-development/MockApplicationAnimator.js
  src/scenes/UIStore.js
  src/scenes/Wallet/Components/PaymentsTable/PaymentRow.js
  src/scenes/Wallet/Stores/PaymentRowStore.js
  src/scenes/Wallet/Stores/WalletSceneStore.js
  test/core-stores/Wallet/Wallet.js
  test/core/Mocks/Application.js
  test/core/Mocks/Payment.js
  test/core/Mocks/PriceFeed.js
  test/core/Mocks/Wallet.js
  test/core/application/Application.js
  test/es6.js
  test/preload-polyfill.js
  test/ui/OnboardingStore/index.js
  test/ui/UIStore/UIStore.js
Labels: UI, UX, Wallet, enhancement

#821 fix duplicate payment store being created when sending payments
  src/core-stores/Wallet/WalletStore.js
  src/scenes/UIStore.js
  test/core-stores/Wallet/Wallet.js
Labels: Wallet, bug

#844 Faucet integration
  src/component-development/MockApplicationAnimator.js
  src/component-development/PaymentsTable/index.js
  src/component-development/index.js
  src/components/Dialog/Dialog.js
  src/core-stores/Application/ApplicationStore.js
  src/core/Application/Application.js
  src/core/Application/faucet.js
  src/core/ApplicationSettings/ApplicationSettings.js
  src/index.js
  src/scenes/Application/Stores/ApplicationNavigationStore.js
  src/scenes/Downloading/components/StartDownloadingFlow/StartDownloadingFlow.js
  src/scenes/Downloading/components/TorrentTable.js
  src/scenes/UIStore.js
  src/scenes/Wallet/Components/ClaimFreeBCHFlowDialog/ClaimFreeBCHFlowDialog.js
  src/scenes/Wallet/Components/ClaimFreeBCHFlowDialog/FailedForm.js
  src/scenes/Wallet/Components/ClaimFreeBCHFlowDialog/SuccessForm.js
  src/scenes/Wallet/Components/ClaimFreeBCHFlowDialog/WaitingForServerReplyForm.js
  src/scenes/Wallet/Components/ClaimFreeBCHFlowDialog/index.js
  src/scenes/Wallet/Components/LiveWalletSceneContent.js
  src/scenes/Wallet/Components/PaymentsTable/PaymentsTableBody.js
  src/scenes/Wallet/Components/ReceiveDialog/ReceiveDialog.js
  src/scenes/Wallet/Components/ReceiveDialog/StringForm.js
  src/scenes/Wallet/Components/SendDialog/SendDialog.js
  src/scenes/Wallet/Components/SendDialog/TakingUserInputForm.js
  src/scenes/Wallet/Components/SendDialog/UserProvidingAmountForm/UserProvidingAmountForm.js
  src/scenes/Wallet/Components/SendDialog/UserProvidingRecipientAddressForm/UserProvidingRecipientAddressForm.js
  src/scenes/Wallet/Stores/ClaimFreeBCHFlowStore.js
  src/scenes/Wallet/Stores/WalletSceneStore.js
  src/scenes/Wallet/Stores/index.js
  test/core/ApplicationSettings/ApplicationSettings.js
  test/core/Mocks/ApplicationSettings.js
  test/core/Mocks/index.js
  test/core/application/Application.js
  test/ui/Wallet/WalletSceneStore.js
Labels: UX, Wallet, enhancement

#856 Remove applicationstore exceptions
  src/core-stores/Application/ApplicationStore.js
Labels: MOBX, bug

#863 Make MOBX dev tools presence subject to environment variable
  package.json
  src/index.js
Labels: MOBX, enhancement

#868 update(PaymentRow): replace unconfirmed icon|animation
  src/scenes/Wallet/Components/PaymentsTable/PaymentRow.js
Labels: bug

#867 fix: disabled all the async state handling in toolbars
  src/component-development/MockApplicationAnimator.js
  src/components/Toolbar/RemoveAndDeleteSection.js
  src/components/Toolbar/RemoveSection.js
  src/scenes/Completed/components/TorrentToolbar.js
  src/scenes/Downloading/components/TorrentToolbar.js
  src/scenes/Seeding/Components/TorrentToolbar.js
  test/core/Mocks/index.js
Labels: bug

#870 Improving torrent scene labels
  src/components/MiddleSection/BandwidthLabel.js
  src/components/MiddleSection/CurrencyLabel.js
  src/components/MiddleSection/Label.js
  src/components/MiddleSection/SimpleLabel.js
  src/constants.js
  src/scenes/Application/Application.js
  src/scenes/Application/components/ApplicationHeader/WalletPanel.js
  src/scenes/Community/Community.js
  src/scenes/Completed/Completed.js
  src/scenes/Downloading/Downloading.js
  src/scenes/Seeding/Seeding.js
  src/scenes/UIStore.js
  src/scenes/Wallet/Components/PaymentsTable/Header.js
  src/scenes/Wallet/Components/PaymentsTable/PaymentRow.js
  src/scenes/Wallet/Components/PaymentsTable/PaymentsTable.js
  src/scenes/Wallet/Components/PaymentsTable/PaymentsTableBody.js
Labels: UI, enhancement

#876 fix: lowering contrast on labels
  src/components/MiddleSection/BandwidthLabel.js
  src/components/MiddleSection/CurrencyLabel.js
Labels: UI, enhancement

#878 fix broken hovering logic from before
  src/components/Table/Row.js
  src/scenes/Completed/components/TorrentRow.js
  src/scenes/Downloading/components/TorrentRow.js
  src/scenes/Seeding/Components/TorrentRow.js
  src/styles/table.scss
Labels: UI, UX, bug

#872 fixed displaying seen date of unconfirmed payment
  src/scenes/UIStore.js
Labels: bug

#927 Fix misplaced label tooltips
  src/components/MiddleSection/BandwidthLabel.js
  src/components/MiddleSection/CurrencyLabel.js
Labels: UI, bug

#919 Improve key action UX on torrents
  src/components/RowFields/NameField.js
  src/components/RowFields/ProgressField.js
  src/components/Table/Field.js
  src/components/Table/Row.js
  src/components/Table/Table.js
  src/scenes/Completed/components/ControlUploadingButtonField.js
  src/scenes/Completed/components/TorrentRow.js
  src/scenes/Completed/components/TorrentTable.js
  src/scenes/Completed/components/TorrentToolbar.js
  src/scenes/Downloading/components/StartPaidDownloadingField.js
  src/scenes/Downloading/components/TorrentRow.js
  src/scenes/Downloading/components/TorrentTable.js
  src/scenes/Downloading/components/TorrentToolbar.js
  src/scenes/Seeding/Components/TorrentRow.js
  src/styles/_constants.scss
  src/styles/react-tooltip-overrides.scss
  src/styles/table.scss
Labels: UI, UX

#926 enhance(WelcomeScreenContent): add missing spacer
  src/scenes/Onboarding/WelcomeScreen/WelcomeScreenContent.js
Labels: Onboarding, UI, bug

#898 call play on video element when video player component mounts
  src/components/VideoPlayer/VideoPlayer.js
Labels: Mediaplayer, UI

#924 Add explainers
  src/components/Table/ExplainedHeaderLabel.js
  src/components/Table/StringHeaderLabel.js
  src/components/Table/Table.js
  src/components/Table/TableBody.js
  src/components/Table/TableHeader.js
  src/components/Table/index.js
  src/scenes/Completed/components/TorrentTable.js
  src/scenes/Downloading/components/TorrentTable.js
  src/scenes/Seeding/Components/TorrentTable.js
  src/styles/table.scss
Labels: UX, enhancement

#928 Settings in UI
  src/core-stores/Application/ApplicationStore.js
  src/core-stores/ApplicationSettings/ApplicationSettingsStore.js
  src/core-stores/ApplicationSettings/index.js
  src/core-stores/index.js
  src/core/ApplicationSettings/ApplicationSettings.js
  src/scenes/Application/Application.js
  src/scenes/Application/Stores/ApplicationNavigationStore.js
  src/scenes/Application/components/ApplicationHeader/ApplicationHeader.js
  src/scenes/Application/components/ApplicationHeader/Buttons.js
  src/scenes/Downloading/Stores/DownloadingStore.js
  src/scenes/Settings/Settings.js
  src/scenes/Settings/index.js
  src/scenes/UIStore.js
Labels: enhancement

#920 Blocked adding torrent button
  src/components/MiddleSection/ToolbarButton.js
  src/scenes/Downloading/Downloading.js
Labels: UI, UX, enhancement

#923 Smarter migration
  src/core/Application/Application.js
  src/core/ApplicationSettings/ApplicationSettings.js
  src/defaultAppDirectory.js
  src/index.js
  src/main.js
  src/migration.js
  src/migration/index.js
  src/migration/migration_1_0_0_to_1_0_1.js
  src/migration/migration_1_0_1_to_1_0_2.js
  src/migration/migration_testnet_to_1_0_0.js
  src/migration/migrations.js
  src/migration/transformTorrentSettings.js
Labels: Migration, enhancement

#933 Hot fix default terms computation
  src/core-stores/Application/ApplicationStore.js
  src/core/Application/Application.js
  src/scenes/Downloading/Stores/DownloadingStore.js
  src/scenes/Seeding/Stores/UploadingStore.js
Labels: UI, UX, bug

#938 Torrent table hotfix
  src/scenes/Completed/components/TorrentTable.js
  src/scenes/Seeding/Components/TorrentTable.js
Labels: bug

#959 hotfix(piece length): fix for piece length distortion
  src/common/common.js
  src/core/Application/Application.js
  src/scenes/UIStore.js
Labels: bug, enhancement

#962 Fix broken seeding flow
  src/core/Application/Application.js
  src/scenes/Seeding/Components/StartUploadingFlow/DroppingPriorAutoStartedDownload.js
  src/scenes/Seeding/Components/StartUploadingFlow/StartUploadingFlow.js
  src/scenes/Seeding/Stores/UploadingStore.js
Labels: UI, UX, bug

#963 Misc minor fixes
  src/components/MiddleSection/BandwidthLabel.js
  src/main.js
  src/scenes/Downloading/components/StartPaidDownloadingField.js
  src/scenes/Seeding/Components/TorrentRow.js
  src/scenes/Seeding/Components/TorrentTable.js
  src/scenes/Seeding/Seeding.js
  src/scenes/Wallet/Components/ViewHDSeedDialog/ViewHDSeedDialog.js
Labels: UI, UX, bug, enhancement
