Repository JoyStream/joystream-desktop, pull requests merged in 2018-02, with the labels that each got.

#688 Adding torrent stores
  src/core-stores/Torrent/TorrentStore.js
  src/core/Torrent/Statemachine/Loading/Loading.js
  src/core/Torrent/Torrent.js
  src/scenes/Common/TorrentTableRowStore.js
  src/scenes/Common/utils.js
  src/scenes/Completed/Stores/CompletedStore.js
  src/scenes/Downloading/Stores/DownloadingStore.js
  src/scenes/Seeding/Stores/UploadingStore.js
  src/scenes/UIStore.js
Labels: Refactor

#693 Fix ui
  src/components/Toolbar/StartPaidDownloadingSection.js
  src/components/VideoPlayer/StartPaidDownloadButton.js
  src/core-stores/Torrent/TorrentStore.js
  src/core/Application/Application.js
  src/core/Torrent/Statemachine/Active/DownloadIncomplete/Unpaid/Started.js
  src/core/Torrent/Statemachine/Common.js
  src/core/Torrent/Statemachine/Loading/Loading.js
  src/core/Torrent/Torrent.js
  src/core/Torrent/ViabilityOfPaidDownloadingSwarm.js
  src/core/Torrent/index.js
  src/index.js
  src/scenes/Application/Application.js
  src/scenes/Application/components/ApplicationHeader/ApplicationHeader.js
  src/scenes/Common/TorrentTableRowStore.js
  src/scenes/Common/ViabilityOfPaidDownloadingTorrent.js
  src/scenes/Common/utils.js
  src/scenes/Completed/Stores/CompletedStore.js
  src/scenes/Downloading/Downloading.js
  src/scenes/Downloading/Stores/DownloadingStore.js
  src/scenes/Downloading/components/TorrentToolbar.js
  src/scenes/Seeding/Stores/UploadingStore.js
  src/scenes/UIStore.js
  test/core-stores/Torrent/index.js
  test/core/TorrentStatemachine.js
  test/ui/UIStore/MockApplication.js
  test/ui/UIStore/UIStore.js
Labels: Refactor, UI, bug

#705 Continued fixing of ui
  src/components/Table/Row.js
  src/core-stores/Wallet/WalletStore.js
  src/core/Application/Application.js
  src/scenes/Application/Application.js
  src/scenes/Application/Stores/ApplicationNavigationStore.js
  src/scenes/Application/components/ApplicationHeader/ApplicationHeader.js
  src/scenes/Community/Community.js
  src/scenes/Completed/Completed.js
  src/scenes/Completed/Stores/CompletedStore.js
  src/scenes/Downloading/Downloading.js
  src/scenes/Downloading/Stores/DownloadingStore.js
  src/scenes/Downloading/components/TorrentRow.js
  src/scenes/Seeding/Components/TorrentRow.js
  src/scenes/Seeding/Seeding.js
  src/scenes/Seeding/Stores/UploadingStore.js
  src/scenes/UIStore.js
  src/scenes/Wallet/Components/WalletScene.js
Labels: UI, bug

#709 Application: correctly add torrents from database
  src/core/Application/Application.js
Labels: bug

#716 Fix application stop bug
  src/core/Application/Application.js
  src/core/Torrent/Torrent.js
  test/core/application/Application.js
  test/core/application/torrents/tears-of-steel.torrent
Labels: bug

#712 Fixed Media Player
  src/components/VideoPlayer/CloseButton.js
  src/components/VideoPlayer/StartPaidDownloadButton.js
  src/components/VideoPlayer/TorrentStreamProgress.js
  src/core/Application/Application.js
  src/core/Torrent/FileSegmentStreamFactory.js
  src/core/Torrent/Torrent.js
  src/scenes/Common/TorrentTableRowStore.js
  src/scenes/Completed/Stores/CompletedStore.js
  src/scenes/Downloading/Stores/DownloadingStore.js
  src/scenes/Downloading/components/TorrentToolbar.js
  src/scenes/Seeding/Stores/UploadingStore.js
  src/scenes/UIStore.js
  src/scenes/VideoPlayer/Stores/MediaPlayerStore.js
  test/ui/CompletedStore/index.js
  test/ui/DownloadingStore/index.js
  test/ui/UploadingStore/index.js
Labels: UI

#706 Repairing loading|terminating|onboarding
  src/constants.js
  src/core/Application/Application.js
  src/core/index.js
  src/index.js
  src/scenes/Application/Application.js
  src/scenes/Idle/IdleScene.js
  src/scenes/Idle/index.js
  src/scenes/Onboarding/DepartureScreen/DepartureScreen.js
  src/scenes/Onboarding/Stores/OnboardingStore.js
  src/scenes/Onboarding/WelcomeScreen/WelcomeScreen.js
  src/scenes/UIStore.js
  test/core/Mocks/Application.js
  test/core/Mocks/index.js
  test/core/application/Application.js
  test/ui/OnboardingStore/index.js
Labels: MOBX, React, UI, bug

#719 Faster wallet start
  src/core/Wallet/Wallet.js
Labels: Wallet, enhancement

#726 Wallet scene loading ui
  package.json
  src/component-development/MockApplicationAnimator.js
  src/component-development/index.js
  src/core-stores/Application/ApplicationStore.js
  src/core/Wallet/Wallet.js
  src/scenes/Application/components/ApplicationHeader/ApplicationHeader.js
  src/scenes/UIStore.js
  src/scenes/Wallet/Components/LiveWalletSceneContent.js
  src/scenes/Wallet/Components/LoadingWalletSceneContent.js
  src/scenes/Wallet/Components/PaymentsTable/PaymentRow.js
  src/scenes/Wallet/Components/WalletScene.js
  src/scenes/Wallet/Stores/ReceiveDialogStore.js
  src/scenes/Wallet/Stores/WalletSceneStore.js
  test/core/Mocks/Application.js
  test/core/Mocks/Wallet.js
  test/core/Mocks/index.js
  test/core/application/Application.js
  test/ui/UIStore/MockApplication.js
  test/ui/UIStore/UIStore.js
Labels: React, UI, Wallet, bug

#737 fixed visibility of torrent check loader bar
  src/index.js
  src/scenes/Application/Application.js
Labels: bug

#746 Explain disabled scenes
  src/scenes/Application/Application.js
  src/scenes/Application/Stores/ApplicationNavigationStore.js
  src/scenes/Application/components/ApplicationHeader/ApplicationHeader.js
  src/scenes/Application/components/ApplicationHeader/Buttons.js
  src/scenes/Common/SceneExplainerBox.js
  src/scenes/Common/index.js
  src/scenes/Livestream/Livestream.js
  src/scenes/Livestream/index.js
  src/scenes/New/New.js
  src/scenes/New/index.js
  src/scenes/Publish/Publish.js
  src/scenes/Publish/index.js
Labels: React, UI, UX

#735 Fix broken table scroller
  src/component-development/MockApplicationAnimator.js
  src/component-development/index.js
  test/core/Mocks/MockJSNodeTorrent.js
  test/core/Mocks/Torrent.js
  test/core/Mocks/index.js
  test/core/PeerStatemachine.js
  test/core/TorrentStatemachine.js
Labels: bug

#751 Final torrent scenes fix
  src/components/Toolbar/StartUploadingSection.js
  src/core-stores/Application/ApplicationStore.js
  src/core-stores/Torrent/TorrentStore.js
  src/scenes/Common/TorrentTableRowStore.js
  src/scenes/Completed/components/TorrentRow.js
  src/scenes/Completed/components/TorrentTable.js
  src/scenes/Completed/components/TorrentToolbar.js
  src/scenes/Downloading/Stores/DownloadingStore.js
  src/scenes/Downloading/components/TorrentRow.js
  src/scenes/Downloading/components/TorrentTable.js
  src/scenes/Seeding/Components/StartUploadingFlow/IncompleteDownloadWarning.js
  src/scenes/Seeding/Components/StartUploadingFlow/LoadingTorrentForUploading.js
  src/scenes/Seeding/Components/TorrentRow.js
  src/scenes/Seeding/Components/TorrentTable.js
  src/scenes/Seeding/Stores/UploadingStore.js
  src/scenes/UIStore.js
Labels: UI, bug

#762 bug(UploadingStore): use savepath provided from UI
  src/scenes/Seeding/Stores/UploadingStore.js
Labels: UI, bug

#765 Uploading hotfixes
  src/components/FullScreenDialog/FullScreenDialog.js
  src/scenes/UIStore.js
Labels: bug
